version: "3.9"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000

  frontend:
    build:
      context: ./frontend

    ports:
      - "3000:3000"
